### ISSUE TITLE
KSU and SUSFS

### ISSUE THREAD

**Issue by cuongnguyen2190** [hfdem/android_gki_kernel_5.15_common#1]
Hello, is there any chances that we can have a Kernel with KSU and SUSFS embedded ? Thank you

**Comment by hfdem** [comment]
This is a common kernel and I need to ensure stability. I should not add modules that may cause unstable. You can refer to the following links to learn to compile for your own.

https://source.android.com/docs/core/architecture/kernel/gki-releases#is_it_possible_to_reproduce_gki_binaries
https://kernelsu.org/guide/how-to-build.html#build-kernel-with-kernelsu
https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android13-5.15?ref_type=heads#patch-instruction-for-gki-kernel-only-and-building-from-official-google-artifacts
